name: Deploy Dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish
        required: true

env:
  SERVICE_NAME: provider-detective

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, main]
    steps:
      - name: Create directory and set permissions
        run: |
          sudo mkdir -p /home/runner/_work/provider-detective/provider-detective
          sudo chown -R runner:runner /home/runner/_work/provider-detective/provider-detective
          sudo chmod 777 /home/runner/_work/provider-detective/provider-detective

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Checkout icanbwell/cie.gha-deploy
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: icanbwell/cie.gha-deploy
          token: ${{ secrets.BWELL_DEV_PAT }}
          path: .github/actions/cie.gha-deploy

      - name: Deploy
        uses: ./.github/actions/cie.gha-deploy
        with:
          token: ${{ secrets.BWELL_DEV_PAT }}
          service-name: $SERVICE_NAME
          env: 'dev-ue1'
          image-tag: ${{ github.event.inputs.tag }}

  slack-workflow-status:
      if: always()
      name: Post Workflow Status To Slack
      needs:
        - deploy
      runs-on: [self-hosted, main]
      steps:
        - name: Slack Workflow Notification
          uses: Gamesight/slack-workflow-status@master
          with:
            # Required Input
            repo_token: ${{secrets.GITHUB_TOKEN}}
            slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
            # Optional Input
            name: 'ReleaseBot'
            icon_emoji: ':pray:'
            channel: '#bwell-releases-bot-alerts'
